[tox]
envlist = py310,py311,py312,py313
isolated_build = True

[testenv]
deps =
		pytest
		pytest-cov
commands =
		pytest --cov=chert --cov-report=xml:.tox/coverage-{envname}.xml {posargs} tests/

[testenv:coverage-report]
deps = coverage
commands =
		coverage combine
		coverage xml -o .tox/coverage.xml
		coverage report
		coverage html -d htmlcov
